# Generated by Django 4.1.7 on 2023-03-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_paste', '0003_post_post_category_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
