# Generated by Django 4.1.7 on 2023-03-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_paste', '0004_alter_post_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
