# Generated by Django 4.1.7 on 2023-03-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_paste', '0007_alter_post_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url_slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('Plain Text', 'Plain Text'), ('JavaScript', 'Javascript'), ('Python', 'Python'), ('Other Language', 'Other Language')], default='Plain Text', max_length=14),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Notes', 'Notes'), ('Code', 'Code'), ('Temporary File', 'Temp')], default='Notes', max_length=14),
        ),
    ]
