# Generated by Django 4.1.7 on 2023-03-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_paste', '0010_alter_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
