# Generated by Django 4.1.7 on 2023-03-16 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_paste', '0011_alter_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
